const NewsSources = {
    Stratechery: {blogname: 'Stratechery', authorname:'Ben Thompson', url:'https://stratechery.com', avatar:'stratecherry-favicon.png'},
    BenedictEvans: {blogname: 'Benedict Evans', authorname:'Benedict Evans', url:'https://www.ben-evans.com/', avatar:'benedict-evans-favicon.png'},
    ByteByteGo: {blogname: 'ByteByteGo', authorname:'Alex Xu', url:'https://www.bytebytego.com/', avatar:'bytebytego-favicon.png'},
    ThePragmaticEngineer: {blogname: 'The Pragmatic Engineer', authorname:'Gergely Orosz', url:'https://blog.pragmaticengineer.com/', avatar:'the-pragmatic-engineer-favicon.png'},
}

export const NewsPreviewData = [
    {
        id: '1',
        title: 'Benedict\'s Newsletter: No. 444',
        source: NewsSources.BenedictEvans,
        date: 'Tuesday, Jun 21, 2022',
        url: null,
        previewimage: false,
        description: 'Facebook pivots to swiping? The Verge has a leaked memo that Facebook wants to be more like TikTok, with more content in your feed from people you don’t follow, driven by recommendations and interests...',
        like: 1365,
        bookmark: false,
        readingprogress: '45%',
    },
    {
        id: '2',
        title: 'Data and Definitions',
        source: NewsSources.Stratechery,
        date: 'Tuesday, Jun 21, 2022',
        url: null,
        previewimage: false,
        description: 'Note: I’ve covered everything in this Article across a number of other Articles and Updates; however, over the course of conversations about ATT, I realized that I have not summarized in one place why Apple’s approach feels fundamentally unfair, even if you agree with the broader aims...',
        like: 1452,
        bookmark: false,
        readingprogress: '100%',
    },
    {
        id: '5',
        title: 'New System Design YouTube channel | Internationalization | SQL Joins | HTTP error handling',
        source: NewsSources.ByteByteGo,
        date: 'Tuesday, Jun 14, 2022',
        url: null,
        previewimage: true,
        description: '*BIG* announcement: we’ve launched a YouTube channel! The first video is already live and we\'ll try to post new videos weekly...',
        like: 358,
        bookmark: true,
        readingprogress: '100%',
    },
    {
        id: '9',
        title: 'The Scoop: Business as Usual in Parts of the Market',
        source: NewsSources.ThePragmaticEngineer,
        date: 'Thursday, Jun 9, 2022',
        url: null,
        previewimage: true,
        description: 'In the latest issue of The Scoop, sent to full subscribers I analyzed what is really happening across the tech job market...',
        like: 1234,
        bookmark: false,
        readingprogress: '89%',
    },
    {
        id: '9',
        title: 'The Scoop: Business as Usual in Parts of the Market',
        source: NewsSources.ThePragmaticEngineer,
        date: 'Thursday, Jun 9, 2022',
        url: null,
        previewimage: true,
        description: 'In the latest issue of The Scoop, sent to full subscribers I analyzed what is really happening across the tech job market...',
        like: 1234,
        bookmark: false,
        readingprogress: '89%',
    },
    {
        id: '9',
        title: 'The Scoop: Business as Usual in Parts of the Market',
        source: NewsSources.ThePragmaticEngineer,
        date: 'Thursday, Jun 9, 2022',
        url: null,
        previewimage: true,
        description: 'In the latest issue of The Scoop, sent to full subscribers I analyzed what is really happening across the tech job market...',
        like: 1234,
        bookmark: false,
        readingprogress: '89%',
    },
    {
        id: '9',
        title: 'The Scoop: Business as Usual in Parts of the Market',
        source: NewsSources.ThePragmaticEngineer,
        date: 'Thursday, Jun 9, 2022',
        url: null,
        previewimage: true,
        description: 'In the latest issue of The Scoop, sent to full subscribers I analyzed what is really happening across the tech job market...',
        like: 1234,
        bookmark: false,
        readingprogress: '89%',
    },

]